# Generated by Django 4.0.1 on 2022-01-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default=None, max_length=250)),
                ('slug', models.SlugField(blank=True, default=None, max_length=250, unique=True)),
                ('type', models.CharField(blank=True, default=None, max_length=250)),
                ('author', models.CharField(blank=True, default=None, max_length=250)),
                ('caption', models.CharField(blank=True, default=None, max_length=100)),
                ('alt', models.CharField(blank=True, default=None, max_length=100)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('tablet', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('desktop', models.ImageField(blank=True, default=None, upload_to='images/')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
